config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :authorization_forms
    resources :departments
    resources :destinations
    resources :expense_types
    resources :notifications
    resources :payment_managers
    resources :receipts
    resources :receipts_requests
    resources :reim_form_messages
    resources :reimbursement_forms
    resources :requests
    resources :statuses
    resources :trips
    resources :wishes

    root to: "employees#index"
  end

  resources :reim_form_messages
  resources :notifications
  resources :receipts_requests
  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "trips#index", as: 'trip_index'
  resources :authorization_forms
  resources :departments
  resources :expense_types
  resources :receipts
  resources :reimbursement_forms
  resources :requests
  resources :statuses
  resources :trips
  resources :wishes
  
  get 'manage/authform/pending', to: 'manages#authform_index'
  get 'manage/authform/history', to: 'manages#authform_history', as: :manage_auth_history
  get 'manage/authform/:id', to: 'manages#authform_show', as: :manage_auth
  put 'manage/authform/:id', to: 'manages#authform_update', as: :manage_auth_update

  get 'manage/reimform/pending', to: 'manages#reimform_index'
  get 'manage/reimform/history', to: 'manages#reimform_history', as: :manage_reimform_history
  get 'manage/reimform/:id', to: 'manages#reimform_show', as: :manage_reimform
  put 'manage/reimform/:id', to: 'manages#reimform_update', as: :manage_reimform_update
  get 'manage/reimform/index_history/:id', to: 'manages#reimform_history_index', as: :manage_reimform_history_index
  get 'manage/reimform/payment_manager/:id', to: 'manages#reimform_payment_show', as: :manage_reimform_payment_show



  get 'create_receipts/:reimbursement_form' => "reimbursement_forms#create_receipts", as: 'create_receipt_yea'

  get 'routes', to: 'pages#routes'
  get 'dashboard', to: 'pages#dashboard'

  get 'about', to: 'pages#about'

  get 'footprint', to: 'pages#footprint'
  
  namespace :api do
    get 'destination', to: 'pages#getdestination'
    get 'expensiveDest', to: 'pages#getExpensiveDest'
    get 'allstatus', to: 'pages#allstatus'
    get 'deptApproveRate', to: 'pages#deptApproveRate'
    get 'getEmpName', to: 'pages#getEmpName'
  end

end

app/models/receipts_request.rb
class ReceiptsRequest < ApplicationRecord
    belongs_to :department
    belongs_to :status
    belongs_to :reimbursement_forms, optional: true
    
    has_many :receipts, inverse_of: :receipts_request, :dependent => :destroy
    
    validates :department_id,:reimbursement_form_id, presence: true
    validates :total_amount, numericality: {greater_than_or_equal_to: 0.01}

    accepts_nested_attributes_for :receipts, :reject_if => :all_blank, :allow_destroy => true
    
    #after_update :change_status
    
    def change_status
        @reimbursement_forms = ReimbursementForm.find(self.reimbursement_form_id)
        Rails.logger.debug "sadasdasd" + @reimbursement_forms.status_id.to_s
        puts "hello"
        @reimbursement_forms.update_attribute(:status_id, 1)
    end
end

app/controllers/admin/receipts_requests_controller.rb
module Admin
  class ReceiptsRequestsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ReceiptsRequest.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ReceiptsRequest.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/receipts_requests_controller.rb
class ReceiptsRequestsController < ApplicationController
  before_action :set_receipts_request, only: [:show, :edit, :update, :destroy]

  # GET /receipts_requests
  # GET /receipts_requests.json
  def index
    @receipts_requests = ReceiptsRequest.all
  end

  # GET /receipts_requests/1
  # GET /receipts_requests/1.json
  def show
    @receipts = @receipts_request.receipts
  end

  # GET /receipts_requests/new
  def new
    @receipts_request = ReceiptsRequest.new
    @status_id = Status.where(name: "Pending").take.id
    @receipts_request.receipts.build
    
  end

  # GET /receipts_requests/1/edit
  def edit
  end

  # POST /receipts_requests
  # POST /receipts_requests.json
  def create
    @receipts_request = ReceiptsRequest.new(receipts_request_params)
    
    
    
    respond_to do |format|
      if @receipts_request.save
        format.html { redirect_to @receipts_request, notice: 'Receipts request was successfully created.' }
        format.json { render :show, status: :created, location: @receipts_request }
      else
        format.html { render :new }
        format.json { render json: @receipts_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts_requests/1
  # PATCH/PUT /receipts_requests/1.json
  def update
    respond_to do |format|
      if @receipts_request.update(receipts_request_params)
        format.html { redirect_to @receipts_request, notice: 'Receipts request was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipts_request }
      else
        format.html { render :edit }
        format.json { render json: @receipts_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts_requests/1
  # DELETE /receipts_requests/1.json
  def destroy
    
    @receipts_request.destroy
    respond_to do |format|
      format.html { redirect_to receipts_requests_url, notice: 'Receipts request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipts_request
      @receipts_request = ReceiptsRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipts_request_params
      params.require(:receipts_request).permit(:total_amount, :department_id, :status_id, :reimbursement_form_id,
      receipts_attributes: [:id ,:location,:receipt_date,:expense_type_id,:image_url,:cost,:_destroy])
    end
end

app/helpers/receipts_requests_helper.rb
module ReceiptsRequestsHelper
end

app/views/receipts_requests/_form.html.erb
<%= semantic_form_for @receipts_request do |f| %>
  <%= f.inputs do %>
    <%= f.input : total_amount %>
    <%= f.input :department_id %>
    <%= f.input :reimbursement_form_id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/receipts_requests/edit.html.erb
<h1>Editing Receipts Request</h1>

<%= render 'form', receipts_request: @receipts_request %>

<%= link_to 'Show', @receipts_request %> |
<%= link_to 'Back', receipts_requests_path %>

app/views/receipts_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receipts Requests</h1>

<table>
  <thead>
    <tr>
      <th> total amount</th>
      <th>Department</th>
      <th>Reimbursement form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts_requests.each do |receipts_request| %>
      <tr>
        <td><%= receipts_request. total_amount %></td>
        <td><%= receipts_request.department_id %></td>
        <td><%= receipts_request.reimbursement_form_id %></td>
        <td><%= link_to 'Show', receipts_request %></td>
        <td><%= link_to 'Edit', edit_receipts_request_path(receipts_request) %></td>
        <td><%= link_to 'Destroy', receipts_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipts Request', new_receipts_request_path %>

app/views/receipts_requests/new.html.erb
<h1>New Receipts Request</h1>

<%= render 'form', receipts_request: @receipts_request %>

<%= link_to 'Back', receipts_requests_path %>

app/views/receipts_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> total amount:</strong>
  <%= @receipts_request. total_amount %>
</p>

<p>
  <strong>Department:</strong>
  <%= @receipts_request.department_id %>
</p>

<p>
  <strong>Reimbursement form:</strong>
  <%= @receipts_request.reimbursement_form_id %>
</p>

<%= debug @receipts.size%>

<% @receipts.each do |receipts| %>
  <td><%= receipts.expense_type.name %></td>
  <td><%= receipts.cost %></td>
<%end%>

<%= link_to 'Edit', edit_receipts_request_path(@receipts_request) %> |
<%= link_to 'Back', receipts_requests_path %>