config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :authorization_forms
    resources :departments
    resources :destinations
    resources :expense_types
    resources :notifications
    resources :payment_managers
    resources :receipts
    resources :receipts_requests
    resources :reim_form_messages
    resources :reimbursement_forms
    resources :requests
    resources :statuses
    resources :trips
    resources :wishes

    root to: "employees#index"
  end

  resources :reim_form_messages
  resources :notifications
  resources :receipts_requests
  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "trips#index", as: 'trip_index'
  resources :authorization_forms
  resources :departments
  resources :expense_types
  resources :receipts
  resources :reimbursement_forms
  resources :requests
  resources :statuses
  resources :trips
  resources :wishes
  
  get 'manage/authform/pending', to: 'manages#authform_index'
  get 'manage/authform/history', to: 'manages#authform_history', as: :manage_auth_history
  get 'manage/authform/:id', to: 'manages#authform_show', as: :manage_auth
  put 'manage/authform/:id', to: 'manages#authform_update', as: :manage_auth_update

  get 'manage/reimform/pending', to: 'manages#reimform_index'
  get 'manage/reimform/history', to: 'manages#reimform_history', as: :manage_reimform_history
  get 'manage/reimform/:id', to: 'manages#reimform_show', as: :manage_reimform
  put 'manage/reimform/:id', to: 'manages#reimform_update', as: :manage_reimform_update
  get 'manage/reimform/index_history/:id', to: 'manages#reimform_history_index', as: :manage_reimform_history_index
  get 'manage/reimform/payment_manager/:id', to: 'manages#reimform_payment_show', as: :manage_reimform_payment_show



  get 'create_receipts/:reimbursement_form' => "reimbursement_forms#create_receipts", as: 'create_receipt_yea'

  get 'routes', to: 'pages#routes'
  get 'dashboard', to: 'pages#dashboard'

  get 'about', to: 'pages#about'

  get 'footprint', to: 'pages#footprint'
  
  namespace :api do
    get 'destination', to: 'pages#getdestination'
    get 'expensiveDest', to: 'pages#getExpensiveDest'
    get 'allstatus', to: 'pages#allstatus'
    get 'deptApproveRate', to: 'pages#deptApproveRate'
    get 'getEmpName', to: 'pages#getEmpName'
  end

end

app/models/reim_form_message.rb
class ReimFormMessage < ApplicationRecord
    belongs_to :trip
    belongs_to :status
end

app/controllers/admin/reim_form_messages_controller.rb
module Admin
  class ReimFormMessagesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ReimFormMessage.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ReimFormMessage.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reim_form_messages_controller.rb
class ReimFormMessagesController < ApplicationController
  before_action :set_reim_form_message, only: [:show, :edit, :update, :destroy]

  # GET /reim_form_messages
  # GET /reim_form_messages.json
  def index
    @reim_form_messages = ReimFormMessage.all
  end

  # GET /reim_form_messages/1
  # GET /reim_form_messages/1.json
  def show
  end

  # GET /reim_form_messages/new
  def new
    @reim_form_message = ReimFormMessage.new
  end

  # GET /reim_form_messages/1/edit
  def edit
  end

  # POST /reim_form_messages
  # POST /reim_form_messages.json
  def create
    @reim_form_message = ReimFormMessage.new(reim_form_message_params)

    respond_to do |format|
      if @reim_form_message.save
        format.html { redirect_to @reim_form_message, notice: 'Reim form message was successfully created.' }
        format.json { render :show, status: :created, location: @reim_form_message }
      else
        format.html { render :new }
        format.json { render json: @reim_form_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reim_form_messages/1
  # PATCH/PUT /reim_form_messages/1.json
  def update
    respond_to do |format|
      if @reim_form_message.update(reim_form_message_params)
        format.html { redirect_to @reim_form_message, notice: 'Reim form message was successfully updated.' }
        format.json { render :show, status: :ok, location: @reim_form_message }
      else
        format.html { render :edit }
        format.json { render json: @reim_form_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reim_form_messages/1
  # DELETE /reim_form_messages/1.json
  def destroy
    @reim_form_message.destroy
    respond_to do |format|
      format.html { redirect_to reim_form_messages_url, notice: 'Reim form message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reim_form_message
      @reim_form_message = ReimFormMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reim_form_message_params
      params.require(:reim_form_message).permit(:reimbusement_form_id, :message, :status_id)
    end
end

app/helpers/reim_form_messages_helper.rb
module ReimFormMessagesHelper
end

app/views/reim_form_messages/_form.html.erb
<%= semantic_form_for @reim_form_message do |f| %>
  <%= f.inputs do %>
    <%= f.input :trip_id %>
    <%= f.input :message %>
    <%= f.input :status_id %>
    <%= f.input :employee_id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/reim_form_messages/edit.html.erb
<h1>Editing Reim Form Message</h1>

<%= render 'form', reim_form_message: @reim_form_message %>

<%= link_to 'Show', @reim_form_message %> |
<%= link_to 'Back', reim_form_messages_path %>

app/views/reim_form_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reim Form Messages</h1>

<table>
  <thead>
    <tr>
      <th>Reimbusement form</th>
      <th>Message</th>
      <th>Status</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reim_form_messages.each do |reim_form_message| %>
      <tr>
        <td><%= reim_form_message.trip_id %></td>
        <td><%= reim_form_message.message %></td>
        <td><%= reim_form_message.status_id %></td>
        <td><%= reim_form_message.employee_id %></td>
        <td><%= link_to 'Show', reim_form_message %></td>
        <td><%= link_to 'Edit', edit_reim_form_message_path(reim_form_message) %></td>
        <td><%= link_to 'Destroy', reim_form_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reim Form Message', new_reim_form_message_path %>

app/views/reim_form_messages/new.html.erb
<h1>New Reim Form Message</h1>

<%= render 'form', reim_form_message: @reim_form_message %>

<%= link_to 'Back', reim_form_messages_path %>

app/views/reim_form_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reimbusement form:</strong>
  <%= @reim_form_message.trip_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @reim_form_message.message %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reim_form_message.status_id %>
</p>
<p>
  <strong>Status:</strong>
  <%= @reim_form_message.employee_id %>
</p>
<%= link_to 'Edit', edit_reim_form_message_path(@reim_form_message) %> |
<%= link_to 'Back', reim_form_messages_path %>