config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :employees
    resources :authorization_forms
    resources :departments
    resources :destinations
    resources :expense_types
    resources :notifications
    resources :payment_managers
    resources :receipts
    resources :receipts_requests
    resources :reim_form_messages
    resources :reimbursement_forms
    resources :requests
    resources :statuses
    resources :trips
    resources :wishes

    root to: "employees#index"
  end

  resources :reim_form_messages
  resources :notifications
  resources :receipts_requests
  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "trips#index", as: 'trip_index'
  resources :authorization_forms
  resources :departments
  resources :expense_types
  resources :receipts
  resources :reimbursement_forms
  resources :requests
  resources :statuses
  resources :trips
  resources :wishes
  
  get 'manage/authform/pending', to: 'manages#authform_index'
  get 'manage/authform/history', to: 'manages#authform_history', as: :manage_auth_history
  get 'manage/authform/:id', to: 'manages#authform_show', as: :manage_auth
  put 'manage/authform/:id', to: 'manages#authform_update', as: :manage_auth_update

  get 'manage/reimform/pending', to: 'manages#reimform_index'
  get 'manage/reimform/history', to: 'manages#reimform_history', as: :manage_reimform_history
  get 'manage/reimform/:id', to: 'manages#reimform_show', as: :manage_reimform
  put 'manage/reimform/:id', to: 'manages#reimform_update', as: :manage_reimform_update
  get 'manage/reimform/index_history/:id', to: 'manages#reimform_history_index', as: :manage_reimform_history_index
  get 'manage/reimform/payment_manager/:id', to: 'manages#reimform_payment_show', as: :manage_reimform_payment_show



  get 'create_receipts/:reimbursement_form' => "reimbursement_forms#create_receipts", as: 'create_receipt_yea'

  get 'routes', to: 'pages#routes'
  get 'dashboard', to: 'pages#dashboard'

  get 'about', to: 'pages#about'

  get 'footprint', to: 'pages#footprint'
  
  namespace :api do
    get 'destination', to: 'pages#getdestination'
    get 'expensiveDest', to: 'pages#getExpensiveDest'
    get 'allstatus', to: 'pages#allstatus'
    get 'deptApproveRate', to: 'pages#deptApproveRate'
    get 'getEmpName', to: 'pages#getEmpName'
  end

end

app/controllers/admin/reimbursement_forms_controller.rb
module Admin
  class ReimbursementFormsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ReimbursementForm.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ReimbursementForm.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reimbursement_forms_controller.rb
class ReimbursementFormsController < ApplicationController

  before_action :set_reimbursement_form, only: [ :edit, :update, :destroy]
  before_action :set_trip, only: [:show, :new, :edit]

  # GET /reimbursement_forms
  # GET /reimbursement_forms.json
  def index
    @reimbursement_forms = ReimbursementForm.all
  end

  # GET /reimbursement_forms/1
  # GET /reimbursement_forms/1.json
  def show
    @reimbursement_form = ReimbursementForm.find(@trip.reimbursement_form.id)
    @receipts_request = @reimbursement_form.receipts_request
    @requests = @trip.requests
    @total_reimb_budget = 0
    @receipts_request_total = 0
    
    @requests.each do |request|
      @total_reimb_budget += request.amount
    end
    
    @receipts_request.each do |receipts_request|
      @receipts_request_total += receipts_request.total_amount
    end
    
  end

  # GET /reimbursement_forms/new
  def new
    @reimbursement_form = ReimbursementForm.new
    @status_id = Status.where(name: "Pending").take.id
  end

  # GET /reimbursement_forms/1/edit
  def edit
  end
  

  def create_receipts
    @reimbursement_form = ReimbursementForm.find(params[:reimbursement_form])
    @status_id = Status.where(name: "Pending").take.id
    @receipts_request = @reimbursement_form.receipts_request.build
    @receipts = @receipts_request.receipts.build
    @trip = @reimbursement_form.trip
    
    @request = @trip.requests
    
    @message = @trip.reim_form_message.create(trip_id: @trip.id,
                                              status_id: @status_id,
                                              employee_id: current_employee.id,
                                              message: "R")
                                                            
    render 'create_receipts'
  end

  # POST /reimbursement_forms
  # POST /reimbursement_forms.json
  def create
    
    @reimbursement_form = ReimbursementForm.new(reimbursement_form_params)
    @trip = Trip.find(params[:reimbursement_form][:trip_id])

    respond_to do |format|
      if @reimbursement_form.save
        @trip = nil
        format.html { redirect_to create_receipt_yea_path(:reimbursement_form => @reimbursement_form)}
        format.json { render :create_receipts, status: :created, location: @reimbursement_form }
      else
        format.html { render :new }
        format.json { render json: @reimbursement_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reimbursement_forms/1
  # PATCH/PUT /reimbursement_forms/1.json
  def update
    respond_to do |format|
      if @reimbursement_form.update(reimbursement_form_params)
        format.html { redirect_to trip_index_url, notice: 'Reimbursement form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @reimbursement_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reimbursement_forms/1
  # DELETE /reimbursement_forms/1.json
  def destroy
    @reimbursement_form.destroy
    respond_to do |format|
      format.html { redirect_to trip_index_url, notice: 'Reimbursement form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reimbursement_form
      @reimbursement_form = ReimbursementForm.find(params[:id])
    end
  
    def set_trip
      @trip = Trip.find(params[:trip_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    # New Create, need all attribute and table names
    def reimbursement_form_params
      params.require(:reimbursement_form).permit(:status_id, :employee_id, :trip_id, 
      receipts_request_attributes: [:id,:total_amount, :department_id,:status_id, :receipts_request_id,
       receipts_attributes: [:id,:location,:receipt_date,:expense_type_id,:image_url,:cost,:receipts_request_id,:reimbursement_form_id]],
       notification_attributes: [:trip_id,:status_id,:employee_id,:form_id,:form])
    end
    
    
end

app/helpers/reimbursement_forms_helper.rb
module ReimbursementFormsHelper
end

app/views/reimbursement_forms/_display_receipts.html.erb
<div class='nested-fields'>
    <%= f.inputs do %>
        <% @receipts.each do |receipt| %>
          <tr>
            <td><%= receipt.expense_type.name %></td>
            <td><%= number_to_currency receipt.cost %></td>
            <td><%= receipt.location %></td>
            <td><%= receipt.receipt_date %></td>
            <td>
              <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400 float-right"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">Actions:</div>
                  <%= link_to 'Edit', edit_receipt_path(receipt), class: "dropdown-item" %>
                  <%= link_to 'Delete', receipt, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
                </div>
              </div>
            </td>
          </tr>
        <%end%>
    <% end %>
</div>

app/views/reimbursement_forms/_form.html.erb
<%= semantic_form_for reimbursement_form do |form| %>

  <% if reimbursement_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reimbursement_form.errors.count, "error") %> prohibited this reimbursement_form from being saved:</h2>

      <ul>
      <% reimbursement_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
      <%=form.hidden_field :status_id, :value => @status_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :employee_id, :value => current_employee.id %>
  </div>


  <div class="field">
    <%= form.hidden_field :trip_id, :value => @trip.id%>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/reimbursement_forms/_receipt_fields.html.erb
<div class='nested-fields'>
    <%= f.inputs do %>
          <div class="form-group">
            <%= f.label :expense_type %>
            <%= f.collection_select :expense_type_id, ExpenseType.order('name ASC'), :id, :name, {id: :receipt_expense_type}, {class: "form-control"} %>
          </div>
        
          
          <div class="form-group">
            <div class="btn-upload-wrapper">
              <button class="btn-upload">Upload Image</button>
              <%= f.file_field :image, id: :receipt_image, class: "myfile"%>
              <label id="image-label"> </label>
            </div>
          </div>
        
        <div class="field">
          <%= f.hidden_field :reimbursement_form_id, :value => @reimbursement_form.id %>
        </div>
        
        <div class="field">
          <%= f.hidden_field :receipts_request_id, :value => @receipts_request.id %>
        </div>
        
          <div class="form-group">
            <%= f.label :cost %>
            <%= f.number_field :cost, id: :receipt_cost, class: "form-control"%>
          </div>

           <div class="form-group">
              <%= f.label :location %>
              <%= f.text_field :location, id: :receipt_location, class: "form-control" %>
            </div>
          
          <div class="form-group">
            <%= f.label :receipt_date %>
            <%= f.text_field :receipt_date, data:{ provide:'datepicker' }, class: "form-control" %>
          </div>
          
        <%= link_to_remove_association f, { :class => "float-right"} do %>
            <i class="fas fa-minus-circle"></i>
        <% end %>

    <% end %>
</div>

<%= javascript_tag do %>
  if(document.getElementById("receipt_image")!=null){
    document.getElementById("receipt_image").addEventListener("input", function(){
    var fullPath = this.value;
    var filename = fullPath.replace(/^.*[\\\/]/, '');
    document.getElementById("image-label").innerHTML = filename;
   });
  }
<% end %>

app/views/reimbursement_forms/_receipts_request_fields.html.erb
<div class = 'nested-fields'>
    <%= f.inputs do %>
    
        <div class="form-group">
              <%= f.label :department %>
              <%= f.collection_select :department_id, Department.order('name ASC'), :id, :name, {id: :request_department}, {class: "form-control"} %>
        </div>
        
        <div class="receipts">
            <%= f.label :receipts %>
            <%= f.semantic_fields_for :receipts, Receipt.new do |receipt| %>
              <%= render 'receipt_fields', :f => receipt%>
            <% end %>
            <div class='links'>
              <%= link_to_add_association f, :receipts do %>
                  <i class="fas fa-plus-circle"></i>
              <% end %>
            </div>
        </div>
        
         <div class="field">
          <%= f.hidden_field :status_id, :value => @status_id %>
        </div>
        
        <div class="field">
          <%= f.hidden_field :reimbursement_form_id, :value => @reimbursement_form.id %>
        </div>
        
        <div class="field">
              <%= f.label :total_amount %>
              <%= f.number_field :total_amount, id: :total_amount, class: "form-control"%>
       </div>
       
        <%= link_to_remove_association f, { :class => "float-right"} do %>
            <i class="fas fa-minus-circle"></i>
        <% end %>
   
   <%end%>
</div>

app/views/reimbursement_forms/_request_fields.html.erb
<div class='nested-fields'>
    <%= f.inputs do %>
        <div class="form-group">
          <%= f.label :department %>
          <%= f.collection_select :department_id, Department.order('name ASC'), :id, :name, {id: :request_department}, {class: "form-control"} %>
        </div>
        
        <div class="form-group">
          <%= f.label :amount %>
          <%= f.number_field :amount, id: :request_amount, class: "form-control"%>
        </div>
        
        <%= link_to_remove_association f, { :class => "float-right"} do %>
            <i class="fas fa-minus-circle"></i>
        <% end %>
    <% end %>
</div>

app/views/reimbursement_forms/_show.html.erb
<%= link_to 'Back', trips_path, class: "btn btn-primary" %>
<%= link_to 'Delete', @reimbursement_form, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right" %>


</br></br>
<div class="row">
  <div class="col-xl-6 col-md-6 mb-6">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Reimbursement Form Status</div>
      </div>
      <div class="card-body">
        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @reimbursement_form.status.name %></div>
      </div>
    </div>
  </div>
  
  <div class="col-xl-6 col-md-6 mb-6">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Authorization Form Status</div>
      </div>
      <div class="card-body">
        <%= @trip.authorization_form ? (link_to @trip.authorization_form.status.name, @trip)
            : (link_to "Not yet submitted", new_authorization_form_path(:trip_id => @trip.id)) %>
      </div>
    </div>
  </div>
</div>

<br><br>

<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400 float-right"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Actions:</div>
          <%= link_to 'Edit', edit_trip_path(@trip), class: "dropdown-item" %>
        </div>
      </div>
    </div>
  <div class="card-body">
    <div class="row no-gutters align-items-center">
      <div class="col mr-2">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Destination</div>
        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= trip_destination(@trip.destination) %></div>
      </div>
      <div class="col mr-2">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Departure Date</div>
        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @trip.date_start %></div>
      </div>
      <div class="col mr-2">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Return Date</div>
        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @trip.date_end %></div>
      </div>
      <div class="col-auto">
        <i class="fas fa-calendar fa-2x text-gray-300"></i>
      </div>
    </div>
    </br>
    <div class="row">
      <div class="col mr-2">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Purpose</div>
        <div class="h6 mb-0 font-weight-bold text-gray-800"><%= @trip.purpose %></div>
      </div>
    </div>
  </div>
</div>

</br>
</br>

<div class="row">
  <div class="col-xl-12 col-md-12 mb-12">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Receipt</div>
      </div>
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="table-responsive text-center">
              <table class="table table-borderless">
                <tbody>
              
                  <% @receipts_request.each do |receipts_request| %>
                    <% @id = receipts_request.id%>
                    <% @receipts = @reimbursement_form.receipts.where(receipts_request_id: @id, reimbursement_form_id: @reimbursement_form.id) %>
                    
                    <thead class="thead-light">
                      <tr >
                        <th align="right">Request from Department Name:</th>
                        <th ><%= receipts_request.department.name%></th>
                        <th align="right">Status of the Receipt Request:</th>
                        <th><%= receipts_request.status.name%></th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
                    <thead class="thead-light">
                      <tr>
                        <th>Type</th>
                        <th>Cost</th>
                        <th>Location</th>
                        <th>Receipt Date</th>
                        <th colspan="1"></th>
                      </tr>
                    </thead>
                    <%@each_receipts_amount =0%>

                    <% @receipts.each do |receipt| %>
                      <tr>
                        
                        <%@each_receipts_amount += receipt.cost%>
                        <td><%= receipt.expense_type.name %></td>
                        <td><%= number_to_currency receipt.cost %></td>
                        <td><%= receipt.location %></td>
                        <td><%= receipt.receipt_date %></td>
                        <% if @reimbursement_form.status.name != "Approved"%>
                          <td>
                            <div class="dropdown no-arrow">
                              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400 float-right"></i>
                              </a>
                              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <div class="dropdown-header">Actions:</div>
                                <%= link_to 'Edit', edit_receipt_path(receipt), class: "dropdown-item" %>
                                <%= link_to 'Delete', receipt, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
                              </div>
                            </div>
                          </td>
                        <%end%>
                      </tr>
                    <%end%>
                     <% @nonono = @each_receipts_amount - receipts_request.total_amount %>
                     
                      <% if @nonono > 0%>
                        <% receipts_request.update_attribute(:total_amount, @each_receipts_amount)%>
                      <%end%>
                    
                      <thead class="thead-dark">
                      <tr >
                        <th align="right">Total Cost:</th>
                        <th ><%= receipts_request.total_amount%></th>
                        <th colspan="3"></th>
                      </tr>
                      </thead>
                      <thead>
                        <tr>
                          <th>
                            
                          </th>
                          <th>
                            
                          </th>
                        </tr>
                      </thead>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-gift fa-2x text-gray-300"></i>
          </div>
        </div>
        </br>
      </div>
    </div>
  </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-xl-12 col-md-12 mb-12">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Requests</div>
      </div>
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="table-responsive text-center">
              <table class="table table-borderless">
                <thead class="thead-light">
                  <tr>
                    <th>Department</th>
                    <th>Amount Request</th>
                    <th>Status</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @requests.each do |request| %>
                    <tr>
                      <td><%= request.department.name %></td>
                      <td><%= number_to_currency request.amount %></td>

                      <td><%= request.status.name %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-money-check-alt fa-2x text-gray-300"></i>
          </div>
        </div>
        </br>
      </div>
    </div> 
  </div>
  </div>
  
  <br>
  <div class="row">
      <div class="col-xl-12 col-md-12 mb-12">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Your Request Status Report</div>
      </div>
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="table-responsive text-center">
              <table class="table table-borderless">
                <thead class="thead-light">
                  <tr>
                    <th>Total Request Amount</th>
                    <th>Total receipt Request Amount</th>
                    <th>Balance</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <%= @total_reimb_budget%>
                    </td>
                    <td>
                      <%= @receipts_request_total%>
                    </td>
                    <td>
                      <% @balance = @total_reimb_budget - @receipts_request_total %>
                      
                      <% if @balance < 0 %>
                        <%= flash[:error] = "Warning! You need check your balance $ " + @balance.to_s%>
                      <%else%>
                        <%=@balance%>
                      <%end%>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-money-check-alt fa-2x text-gray-300"></i>
          </div>
        </div>
        </br>
      </div>
    </div> 
  </div>
  </div>
  
  </br>
  </br>

app/views/reimbursement_forms/create_receipts.html.erb
<%= semantic_form_for @reimbursement_form do |form| %>

    <% if @reimbursement_form.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reimbursement_form.errors.count, "error") %> prohibited this reimbursement_form from being saved:</h2>
    
          <ul>
          <% @reimbursement_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>
      
      
      <div class="col-xl-12 col-md-12 mb-12">
    <div class="card shadow h-100 py-2">
      <div class="card-header">
        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Requests</div>
      </div>
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="table-responsive text-center">
              <table class="table table-borderless">
                <thead class="thead-light">
                  <tr>
                    <th>Department</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @request.each do |request| %>
                    <tr>
                      <td><%= request.department.name %></td>
                      <td><%= number_to_currency request.amount %></td>
                      <td><%= request.status.name %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
      
      <br>
      
    <div class="receipts_request">
        <%= form.label :receipts_request %>
        <%= form.semantic_fields_for :receipts_request, ReceiptsRequest.new do |receipt_reqest| %>
          <%= render 'receipts_request_fields', :f => receipt_reqest%>
        <% end %>
        <div class='links'>
          <%= link_to_add_association form, :receipts_request do %>
              <i class="fas fa-plus-circle"></i>
          <% end %>
        </div>
    </div>
    

    
    
  <div class="actions">
    <%= form.submit %>
  </div>
  
<%end%>

app/views/reimbursement_forms/edit.html.erb
<h1>Editing Reimbursement Form</h1>

<%= render 'form', reimbursement_form: @reimbursement_form %>

<%= link_to 'Show', @reimbursement_form %> |
<%= link_to 'Back', reimbursement_forms_path %>

app/views/reimbursement_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authorization Forms</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Employee</th>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reimbursement_forms.each do |reimbursement_form| %>
      <tr>
        <td><%= reimbursement_form.status_id %></td>
        <td><%= reimbursement_form.employee_id %></td>
        <td><%= reimbursement_form.trip_id %></td>
        <td><%= link_to 'Show', reimbursement_form %></td>
        <td><%= link_to 'Edit', edit_reimbursement_form_path(reimbursement_form) %></td>
        <td><%= link_to 'Destroy', reimbursement_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authorization Form', new_reimbursement_form_path %>

app/views/reimbursement_forms/new.html.erb
<h1>New Reimbursement Form</h1>

<%= render 'form', reimbursement_form: @reimbursement_form %>
<%= link_to 'Back', reimbursement_forms_path %>

app/views/reimbursement_forms/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'show', reimbursement_form: @reimbursement_form %>